# Generated by Django 4.0 on 2021-12-20 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userloginactivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLoginActivity',
        ),
    ]
