# Generated by Django 4.0 on 2021-12-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analitics', '0002_userloginactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userloginactivity',
            name='session_key',
        ),
    ]
